version: '3.5'

services:
  template:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/" ]
      interval: 200s
      timeout: 200s
      retries: 5
    ports:
      - 9000:9000
    volumes:
      - .:/golang


